### ISSUE TITLE
Error with cpp code

### ISSUE THREAD

**Issue by mathbunnyru** [gaearon/gitbook-plugin-prism#16]
Can you help me with an error please?
I get an error like this:
```
Failed to load prism syntax: cpp
TypeError: Cannot set property 'keyword' of undefined
    at Object.extend (/Users/mathbunnyru/Documents/work/documentation/node_modules/prismjs/prism.js:79:15)
    at Object.<anonymous> (/Users/mathbunnyru/Documents/work/documentation/node_modules/prismjs/components/prism-cpp.js:1:101)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.code (/Users/mathbunnyru/Documents/work/documentation/node_modules/gitbook-plugin-prism/index.js:64:11)
```

**Comment by mathbunnyru** [comment]
Sorry, I chose ```c++ instead of ```c

**Comment by CXJoyce** [comment]
I want to know how to solve this issue

**Comment by mathbunnyru** [comment]
@CXJoyce I'm sorry, I don't use this plugin anymore and didn't use it for longer than a couple of minutes. I think there was some simple error like changing cpp to c++.

**Comment by robmcguinness** [comment]
The following should work:

````
```cpp
\#include <iostream>
using namespace std;

int main()
{
    cout &lt;&lt; "Hello, World!";
    return 0;
}
```
````

what version of plugin are you using?
