### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sunnyingit** [gaearon/gitbook-plugin-prism#24]
install prism plugin occurs error:
gitbook -d serve
TypeError: Cannot read property 'name' of undefined
    at module.exports.hooks.init (/Users/sunlili/workspace/book/node_modules/gitbook-plugin-prism/index.js:120:46)
    at /Users/sunlili/.gitbook/versions/2.4.3/lib/plugin.js:162:25
    at _fulfilled (/Users/sunlili/.gitbook/versions/2.4.3/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/sunlili/.gitbook/versions/2.4.3/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/sunlili/.gitbook/versions/2.4.3/node_modules/q/q.js:749:13)
    at /Users/sunlili/.gitbook/versions/2.4.3/node_modules/q/q.js:810:14
    at flush (/Users/sunlili/.gitbook/versions/2.4.3/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

gitbook -V
CLI version: 2.3.0
GitBook version: 2.4.3

book.json:

{
    "plugins": ["prism", "-highlight"],
    "pluginsConfig": {
      "prism": {
        "css": [
          "prismjs/themes/prism-okaidia.css"
        ]
      }
    }
}

**Comment by robmcguinness** [comment]
I am not able to recreate using https://github.com/robmcguinness/gitbook-prism-example as the example.  Can you setup a sample repo with the issue?

**Comment by heyheyjp** [comment]
Also having this issue.

CLI version: 2.3.0
GitBook version: 2.6.7

**Comment by robmcguinness** [comment]
I'm using:

```
~/Code/temp/gitbook-prism-example master
❯ node ./node_modules/.bin/gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
```

I'll try with older version of gitbook.

**Comment by robmcguinness** [comment]
Please try with latest release.  It appears the plugin was not compatible with `2.x.x` version of the Gitbook CLI.
