### ISSUE TITLE
Error: Cannot find module 'prismjs/components/prism-yml.js'

### ISSUE THREAD

**Issue by JoeyBling** [gaearon/gitbook-plugin-prism#38]
gitbook version `3.2.3`

```bash
{ Error: Cannot find module 'prismjs/components/prism-yml.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireSyntax (/myBook/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/myBook/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: yml
{ Error: Cannot find module 'prismjs/components/prism-yml.js'
```

**Comment by JoeyBling** [comment]
ok,I have solved it.Change 'shell' to 'bash'

**Comment by JoeyBling** [comment]
ok,I have solved it.Change `shell` to `bash`
