### ISSUE TITLE
Error: Cannot find module 'prismjs/components/prism-text.js'

### ISSUE THREAD

**Issue by yiluxiangbei87110** [gaearon/gitbook-plugin-prism#40]
I have installed this module，why? please give me a hand.

```js

info: loading plugin "theme-default"... OK
info: found 110 pages
info: found 361 asset files
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
warn: "this.generator" property is deprecated, use "this.output.name" instead
warn: "navigation" property is deprecated
warn: "book" property is deprecated, use "this" directly instead
Failed to load prism syntax: text
{ Error: Cannot find module 'prismjs/components/prism-text.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireSyntax (E:\sdkDOC\tianmu-doc\node_modules\gitbook-plugin-prism\index.js:31:3)
    at Object.code (E:\sdkDOC\tianmu-doc\node_modules\gitbook-plugin-prism\index.js:103:11)
    at Record.TemplateBlock.applyBlock (C:\Users\Felix\.gitbook\versions\3.2.3\lib\models\templateBlock.js:205:23)
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\getModifiers.js:56:33
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\modifiers\highlightCode.js:47:24
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\modifiers\editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: text
{ Error: Cannot find module 'prismjs/components/prism-text.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireSyntax (E:\sdkDOC\tianmu-doc\node_modules\gitbook-plugin-prism\index.js:31:3)
    at Object.code (E:\sdkDOC\tianmu-doc\node_modules\gitbook-plugin-prism\index.js:103:11)
    at Record.TemplateBlock.applyBlock (C:\Users\Felix\.gitbook\versions\3.2.3\lib\models\templateBlock.js:205:23)
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\getModifiers.js:56:33
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\modifiers\highlightCode.js:47:24
    at C:\Users\Felix\.gitbook\versions\3.2.3\lib\output\modifiers\editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
info: >> generation finished with success in 21.2s !


```

![image](https://user-images.githubusercontent.com/23131032/70966012-9eed7200-20cc-11ea-8cb6-775b60fe2b64.png)

**Comment by yiluxiangbei87110** [comment]
add the file prism-text.js，and it works well . the content is same with prism-textlie.js.


![image](https://user-images.githubusercontent.com/23131032/70970099-766b7500-20d8-11ea-86ef-60fa86816f78.png)
