### ISSUE TITLE
Failed to load prism syntax: gotemplate

### ISSUE THREAD

**Issue by jk2K** [gaearon/gitbook-plugin-prism#41]
```
{ Error: Cannot find module 'prismjs/components/prism-gotemplate.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at requireSyntax (/Users/yemeng1/Documents/codes/go/src/golang-ship/runtime/git/avatar-mpaas/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/Users/yemeng1/Documents/codes/go/src/golang-ship/runtime/git/avatar-mpaas/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/Users/yemeng1/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /Users/yemeng1/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /Users/yemeng1/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /Users/yemeng1/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
```

not support `go` keyword, https://prismjs.com/#supported-languages

**Comment by lucumt** [comment]
It seems you can use `lang` to make an alias for it
